# здесь настройки для data jpa
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    data: data.sql
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

    open-in-view: false

  shell:
    interactive:
      enabled: true

  jmx:
    enabled: true

  data:
    rest:
      base-path: /datarest


logging:
  level:
    ROOT: DEBUG
  file:
    name: C:\\JAVA_LOGS\\app.log


#  batch:
#    job:
#      enabled: false

## оставлю для завтрашнего себя. работа с монгой
##spring:
#  data:
#    mongodb:
#      port: 0
##      port: 27017
#      database: books
#      host: localhost
##      initialization-mode: always
##

##
#mongock:
#  #runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
#  change-logs-scan-package:
#    - ru.otus.spring.mongock.changelog