# здесь настройки для data jpa
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    data: data.sql
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  shell:
    interactive:
      enabled: true

  batch:
    job:
      enabled: false

# оставлю для завтрашнего себя. работа с монгой
#spring:
  data:
    mongodb:
      port: 0
#      port: 27017
      database: books
      host: localhost
#      initialization-mode: always
#
#logging:
#  level:
#    ROOT: ERROR
#
mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog


app:
  ages-count-to-add: 1
  input-file: entries.csv
  output-file: output.dat